---
- name: Upgrade JDK 
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check latest JDK version
      get_url:
        url: "https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.rpm"
        return_content: yes
      register: latest_jdk_version

    - name: Get current JDK version from base image
      command: docker run --rm grpraveenkumar/jdk-tomcat-ansible java -version 2>&1 | awk -F '"' '/version/ {print $2}'
      register: current_jdk_version

    - name: Compare JDK versions
      set_fact:
        is_jdk_update_required: "{{ latest_jdk_version.content != current_jdk_version.stdout }}"

    - name: Recreate base image with latest JDK
      block:
        - name: Build base image
          command: docker build -t grpraveenkumar/jdk-tomcat-ansible .
          args:
            chdir: /path/to/dockerfile

        - name: Stop and remove existing container
          command: docker stop jdktomcatcontainer && docker rm jdktomcatcontainer
          ignore_errors: true

        - name: Start container with updated image
          command: docker run -d --name jdktomcatcontainer -p 8080:8080 grpraveenkumar/jdk-tomcat-ansible
      when: is_jdk_update_required

    - name: Send email notification
      mail:
        host: smtp.example.com
        port: 587
        username: letter2praveenkumar.com
        password: password
        to: admin@praveenfosys.com
        subject: JDK upgrade on Tomcat image
        body: JDK has been upgraded to the latest version.
      when: is_jdk_update_required
      
      
